# NumPy 

The name NumPy is derived from "Numerical Python extensions".
NumPy is a Python library used primarily for computing involving numbers. It is especially useful as it provides a multidimensional array object, called an array.
In addition, NumPy also offers numerous other mathematical functions used in the domain of Linear Algebra and Calculus.


The Pandas module mainly works with the tabular data, whereas the NumPy module works with the numerical data. The Pandas provides some sets of powerful tools like DataFrame and Series that mainly used for analyzing the data, whereas in NumPy module offers a powerful object called Array.



## Using NumPy


In [1]:
import numpy as np
import pandas as pd

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
my_array = np.array(my_list)

In [4]:
type(my_array)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Arange

Return evenly spaced values within a given interval. For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

In [147]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

step : number, optional
    Spacing between values. 
    The default step size is 1.  

In [148]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones

Generate arrays of zeros or ones

In [83]:
np.zeros(3)

array([0., 0., 0.])

In [84]:
np.zeros((10,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [149]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

The NumPy linspace function (sometimes called np.linspace) is a tool in Python for creating numeric sequences. It’s somewhat similar to the NumPy arange function, in that it creates sequences of evenly spaced numbers structured as a NumPy array. Essentally, you specify a starting point and an ending point of an interval, and then specify the total number of breakpoints you want within that interval (including the start and end points). The np.linspace function will return a sequence of evenly spaced values on that interval.

In [60]:
#np.arange(start = 0, stop = 10, step = 3)

In [151]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

The below code will produce 3, equally spaced values from 0 to 10

In [169]:
np.linspace(start = 0, stop = 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [152]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [153]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [156]:
np.random.rand(2)

array([0.60595997, 0.92630088])

In [157]:
np.random.rand(5,5)

array([[0.65107703, 0.91495968, 0.85003858, 0.44945067, 0.09541012],
       [0.37081825, 0.66884125, 0.66592236, 0.59129779, 0.27472179],
       [0.56124343, 0.38292687, 0.9717121 , 0.84891382, 0.72172952],
       [0.23598492, 0.25606832, 0.04043359, 0.71066289, 0.11089082],
       [0.4393365 , 0.2017192 , 0.8957636 , 0.47537022, 0.56327557]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [111]:
np.random.randn(2)

array([ 0.37569802, -0.60063869])

In [112]:
np.random.randn(5,5)

array([[-0.29169375, -0.60170661,  1.85227818, -0.01349722, -1.05771093],
       [ 0.82254491, -1.22084365,  0.2088636 , -1.95967012, -1.32818605],
       [ 0.19686124,  0.73846658,  0.17136828, -0.11564828, -0.3011037 ],
       [-1.47852199, -0.71984421, -0.46063877,  1.05712223,  0.34361829],
       [-1.76304016,  0.32408397, -0.38508228, -0.676922  ,  0.61167629]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [159]:
np.random.randint(1,10)

5

In [160]:
np.random.randint(1,100, 10)

array([23, 15, 43, 29, 36, 13, 32, 71, 59, 86])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [161]:
arr = np.arange(0, 25)
random_array = np.random.randint(0,50,10)

In [162]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [163]:
random_array

array([27,  1, 41, 44,  5, 27, 27, 43, 43, 19])

## Reshape
Returns an array containing the same data with a new shape.

In [192]:
array_1 = np.arange(0, 21)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [195]:
array_1.reshape(5,4)

ValueError: cannot reshape array of size 21 into shape (5,4)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [172]:
random_array

array([27,  1, 41, 44,  5, 27, 27, 43, 43, 19])

In [173]:
#return the maximum along a given axis.
random_array.max()

44

In [171]:
random_array

array([27,  1, 41, 44,  5, 27, 27, 43, 43, 19])

In [175]:
#Return indices of the maximum values along the given axis.
random_array.argmax()

3

In [176]:
random_array.min()

1

In [177]:
#Return indices of the min values along the given axis.
random_array.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [178]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [180]:
variable_1 = arr.reshape(5,5)

In [181]:
variable_1.shape

(5, 5)

In [182]:
my_matrix = np.array([[1,2], [3, 4], [5, 6]])

In [185]:
my_matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [184]:
my_matrix.shape

(3, 2)

In [186]:
my_matrix.ndim

2

In [201]:
np.array([3, 6, 9, 12]) + np.array([4, 10, 2, 1])

array([ 7, 16, 11, 13])

In [197]:
my_list = [3, 6, 9, 12]

In [198]:
my_list/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [203]:
my_list  + [3]

[3, 6, 9, 12, 3]